[mgr]
layout = [ 1, 4, 3 ]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_filter = "lanczos3"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
    { run = '${EDITOR:=vi} "$@"', block = true, desc = "Edit" },
]
open = [
    { run = 'open "$@"', desc = "Open" },
]
